"""empty message

Revision ID: 06e18bdc4682
Revises: e4506871fc3b
Create Date: 2017-11-21 22:02:45.025000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e18bdc4682'
down_revision = 'e4506871fc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_customs_declaration', sa.Column('refund_reason', sa.String(length=200), nullable=True))
    op.add_column('import_customs_declaration', sa.Column('refund_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_customs_declaration', 'refund_reason')
    op.drop_column('export_customs_declaration', 'refund_reason')
    # ### end Alembic commands ###
