"""empty message

Revision ID: 617fb81d266e
Revises: c9aadbf95e78
Create Date: 2017-11-13 15:01:29.074000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '617fb81d266e'
down_revision = 'c9aadbf95e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_mode', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('pay_mode', 'names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_mode', sa.Column('names', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=False))
    op.drop_column('pay_mode', 'name')
    # ### end Alembic commands ###
