"""empty message

Revision ID: 7d38e2e2e7cb
Revises: def57f14eac5
Create Date: 2017-11-20 21:12:50.675000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d38e2e2e7cb'
down_revision = 'def57f14eac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('tax_rate', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rate')
    # ### end Alembic commands ###
