"""empty message

Revision ID: 8d2780646012
Revises: 
Create Date: 2017-11-12 18:19:25.935000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2780646012'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_customs_declaration', sa.Column('agreement_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'import_customs_declaration', ['agreement_id'])
    op.create_foreign_key(None, 'import_customs_declaration', 'import_proxy_agreement', ['agreement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_customs_declaration', type_='foreignkey')
    op.drop_constraint(None, 'import_customs_declaration', type_='unique')
    op.drop_column('import_customs_declaration', 'agreement_id')
    # ### end Alembic commands ###
