"""empty message

Revision ID: 9bbb4e739b6e
Revises: d5371831dcf2
Create Date: 2017-11-21 00:07:59.364000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbb4e739b6e'
down_revision = 'd5371831dcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity', sa.Column('tax_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'tax_price')
    # ### end Alembic commands ###
