"""empty message

Revision ID: a1356e43b431
Revises: 9bbb4e739b6e
Create Date: 2017-11-21 00:09:48.302000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1356e43b431'
down_revision = '9bbb4e739b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'tax_price')
    op.add_column('export_customs_declaration', sa.Column('tax_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('import_customs_declaration', sa.Column('tax_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_customs_declaration', 'tax_price')
    op.drop_column('export_customs_declaration', 'tax_price')
    op.add_column('commodity', sa.Column('tax_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
