"""empty message

Revision ID: afdb6c95587f
Revises: bbe61c9888b2
Create Date: 2017-11-16 19:46:52.463000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afdb6c95587f'
down_revision = 'bbe61c9888b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_customs_declaration', sa.Column('declaration_code', sa.BigInteger(), nullable=True))
    op.drop_index('declaration_cod', table_name='export_customs_declaration')
    op.create_unique_constraint(None, 'export_customs_declaration', ['declaration_code'])
    op.drop_column('export_customs_declaration', 'declaration_cod')
    op.add_column('import_customs_declaration', sa.Column('declaration_code', sa.BigInteger(), nullable=True))
    op.drop_index('declaration_cod', table_name='import_customs_declaration')
    op.create_unique_constraint(None, 'import_customs_declaration', ['declaration_code'])
    op.drop_column('import_customs_declaration', 'declaration_cod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_customs_declaration', sa.Column('declaration_cod', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'import_customs_declaration', type_='unique')
    op.create_index('declaration_cod', 'import_customs_declaration', ['declaration_cod'], unique=True)
    op.drop_column('import_customs_declaration', 'declaration_code')
    op.add_column('export_customs_declaration', sa.Column('declaration_cod', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'export_customs_declaration', type_='unique')
    op.create_index('declaration_cod', 'export_customs_declaration', ['declaration_cod'], unique=True)
    op.drop_column('export_customs_declaration', 'declaration_code')
    # ### end Alembic commands ###
