"""empty message

Revision ID: bb746be3bcf6
Revises: d79ccbb8161d
Create Date: 2017-11-29 06:34:02.285000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb746be3bcf6'
down_revision = 'd79ccbb8161d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'is_active')
    # ### end Alembic commands ###
