"""empty message

Revision ID: bbe61c9888b2
Revises: 617fb81d266e
Create Date: 2017-11-16 19:46:31.859000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe61c9888b2'
down_revision = '617fb81d266e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_customs_declaration', sa.Column('declaration_cod', sa.BigInteger(), nullable=True))
    op.drop_index('declaration_code', table_name='export_customs_declaration')
    op.create_unique_constraint(None, 'export_customs_declaration', ['declaration_cod'])
    op.drop_column('export_customs_declaration', 'declaration_code')
    op.add_column('import_customs_declaration', sa.Column('declaration_cod', sa.BigInteger(), nullable=True))
    op.drop_index('declaration_code', table_name='import_customs_declaration')
    op.create_unique_constraint(None, 'import_customs_declaration', ['declaration_cod'])
    op.drop_column('import_customs_declaration', 'declaration_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_customs_declaration', sa.Column('declaration_code', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=True))
    op.drop_constraint(None, 'import_customs_declaration', type_='unique')
    op.create_index('declaration_code', 'import_customs_declaration', ['declaration_code'], unique=True)
    op.drop_column('import_customs_declaration', 'declaration_cod')
    op.add_column('export_customs_declaration', sa.Column('declaration_code', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=True))
    op.drop_constraint(None, 'export_customs_declaration', type_='unique')
    op.create_index('declaration_code', 'export_customs_declaration', ['declaration_code'], unique=True)
    op.drop_column('export_customs_declaration', 'declaration_cod')
    # ### end Alembic commands ###
