"""empty message

Revision ID: c9aadbf95e78
Revises: 8d2780646012
Create Date: 2017-11-13 15:01:01.272000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9aadbf95e78'
down_revision = '8d2780646012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commodity', 'commodity_name',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200),
               nullable=True)
    op.alter_column('commodity', 'commodity_type',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200),
               nullable=True)
    op.alter_column('commodity', 'hs_code',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=10),
               nullable=True)
    op.alter_column('commodity', 'quantity_and_unit',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100),
               nullable=True)
    op.alter_column('commodity', 'total_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('commodity', 'unit_price',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=True)
    op.alter_column('document', 'name',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100),
               nullable=True)
    op.alter_column('document', 'url',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200),
               nullable=True)
    op.add_column('pay_mode', sa.Column('names', sa.String(length=100), nullable=False))
    op.drop_column('pay_mode', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_mode', sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=False))
    op.drop_column('pay_mode', 'names')
    op.alter_column('document', 'url',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200),
               nullable=False)
    op.alter_column('document', 'name',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100),
               nullable=False)
    op.alter_column('commodity', 'unit_price',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               nullable=False)
    op.alter_column('commodity', 'total_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('commodity', 'quantity_and_unit',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100),
               nullable=False)
    op.alter_column('commodity', 'hs_code',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=10),
               nullable=False)
    op.alter_column('commodity', 'commodity_type',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200),
               nullable=False)
    op.alter_column('commodity', 'commodity_name',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200),
               nullable=False)
    # ### end Alembic commands ###
