"""empty message

Revision ID: d5371831dcf2
Revises: e4c2a2bdd040
Create Date: 2017-11-20 21:58:11.969000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5371831dcf2'
down_revision = 'e4c2a2bdd040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_rate', sa.Column('export_tax_rate', sa.String(length=100), nullable=False))
    op.add_column('tax_rate', sa.Column('import_tax_rate', sa.String(length=100), nullable=False))
    op.drop_column('tax_rate', 'tax_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_rate', sa.Column('tax_rate', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=100), nullable=False))
    op.drop_column('tax_rate', 'import_tax_rate')
    op.drop_column('tax_rate', 'export_tax_rate')
    # ### end Alembic commands ###
