"""empty message

Revision ID: d617c9864a99
Revises: 3a287fbadd93
Create Date: 2017-12-01 13:04:21.057000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd617c9864a99'
down_revision = '3a287fbadd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customs_user', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customs_user', 'is_active')
    # ### end Alembic commands ###
