"""empty message

Revision ID: d79ccbb8161d
Revises: bbeb465b3039
Create Date: 2017-11-27 03:32:03.675000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79ccbb8161d'
down_revision = 'bbeb465b3039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'is_active')
    # ### end Alembic commands ###
