"""empty message

Revision ID: def57f14eac5
Revises: afdb6c95587f
Create Date: 2017-11-19 18:34:01.242000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def57f14eac5'
down_revision = 'afdb6c95587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_customs_declaration', sa.Column('trade_mode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'export_customs_declaration', 'trade_mode', ['trade_mode_id'], ['id'])
    op.add_column('import_customs_declaration', sa.Column('trade_mode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'import_customs_declaration', 'trade_mode', ['trade_mode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_customs_declaration', type_='foreignkey')
    op.drop_column('import_customs_declaration', 'trade_mode_id')
    op.drop_constraint(None, 'export_customs_declaration', type_='foreignkey')
    op.drop_column('export_customs_declaration', 'trade_mode_id')
    # ### end Alembic commands ###
