"""empty message

Revision ID: e4506871fc3b
Revises: a1356e43b431
Create Date: 2017-11-21 00:39:06.604000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4506871fc3b'
down_revision = 'a1356e43b431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('exchage_rate', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'exchage_rate')
    # ### end Alembic commands ###
